// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdsibt3lZN8OF8-UoZnfPaJlGsJz7yxIg',
    appId: '1:504747117714:web:c86a29d0a550471beb2a4b',
    messagingSenderId: '504747117714',
    projectId: 'gbgb-flutter-chat',
    authDomain: 'gbgb-flutter-chat.firebaseapp.com',
    storageBucket: 'gbgb-flutter-chat.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCU2w_qKpyJ4kw11VX8pvD26sp3wzWTfY4',
    appId: '1:504747117714:android:ee14d7d526216b05eb2a4b',
    messagingSenderId: '504747117714',
    projectId: 'gbgb-flutter-chat',
    storageBucket: 'gbgb-flutter-chat.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9XkpS_zFSytqya01Ht6dNaFrUMsdMpm0',
    appId: '1:504747117714:ios:e806dc8a5e46ba0ceb2a4b',
    messagingSenderId: '504747117714',
    projectId: 'gbgb-flutter-chat',
    storageBucket: 'gbgb-flutter-chat.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9XkpS_zFSytqya01Ht6dNaFrUMsdMpm0',
    appId: '1:504747117714:ios:e806dc8a5e46ba0ceb2a4b',
    messagingSenderId: '504747117714',
    projectId: 'gbgb-flutter-chat',
    storageBucket: 'gbgb-flutter-chat.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdsibt3lZN8OF8-UoZnfPaJlGsJz7yxIg',
    appId: '1:504747117714:web:d6375ba7e5c0a63ceb2a4b',
    messagingSenderId: '504747117714',
    projectId: 'gbgb-flutter-chat',
    authDomain: 'gbgb-flutter-chat.firebaseapp.com',
    storageBucket: 'gbgb-flutter-chat.firebasestorage.app',
  );

}